<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Funcionario extends \Application\Entity\Funcionario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'idFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'nomeFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'funcaoFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'cpfFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'rgFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'orgEmissorFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'usuarioFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'senhaFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'dirFotoPfFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'nivelAcessoFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'dataAniversaroFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'situacaoFunc');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'idFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'nomeFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'funcaoFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'cpfFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'rgFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'orgEmissorFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'usuarioFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'senhaFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'dirFotoPfFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'nivelAcessoFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'dataAniversaroFunc', '' . "\0" . 'Application\\Entity\\Funcionario' . "\0" . 'situacaoFunc');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Funcionario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFunc()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFunc();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFunc', array());

        return parent::getIdFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeFunc($nomeFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeFunc', array($nomeFunc));

        return parent::setNomeFunc($nomeFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeFunc', array());

        return parent::getNomeFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuncaoFunc($funcaoFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuncaoFunc', array($funcaoFunc));

        return parent::setFuncaoFunc($funcaoFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuncaoFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuncaoFunc', array());

        return parent::getFuncaoFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpfFunc($cpfFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpfFunc', array($cpfFunc));

        return parent::setCpfFunc($cpfFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpfFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpfFunc', array());

        return parent::getCpfFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setRgFunc($rgFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRgFunc', array($rgFunc));

        return parent::setRgFunc($rgFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRgFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRgFunc', array());

        return parent::getRgFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgEmissorFunc($orgEmissorFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgEmissorFunc', array($orgEmissorFunc));

        return parent::setOrgEmissorFunc($orgEmissorFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgEmissorFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgEmissorFunc', array());

        return parent::getOrgEmissorFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioFunc($usuarioFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioFunc', array($usuarioFunc));

        return parent::setUsuarioFunc($usuarioFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioFunc', array());

        return parent::getUsuarioFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenhaFunc($senhaFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenhaFunc', array($senhaFunc));

        return parent::setSenhaFunc($senhaFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenhaFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenhaFunc', array());

        return parent::getSenhaFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirFotoPfFunc($dirFotoPfFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirFotoPfFunc', array($dirFotoPfFunc));

        return parent::setDirFotoPfFunc($dirFotoPfFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirFotoPfFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirFotoPfFunc', array());

        return parent::getDirFotoPfFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelAcessoFunc($nivelAcessoFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelAcessoFunc', array($nivelAcessoFunc));

        return parent::setNivelAcessoFunc($nivelAcessoFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelAcessoFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelAcessoFunc', array());

        return parent::getNivelAcessoFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAniversaroFunc($dataAniversaroFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAniversaroFunc', array($dataAniversaroFunc));

        return parent::setDataAniversaroFunc($dataAniversaroFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAniversaroFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAniversaroFunc', array());

        return parent::getDataAniversaroFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacaoFunc($situacaoFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacaoFunc', array($situacaoFunc));

        return parent::setSituacaoFunc($situacaoFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacaoFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacaoFunc', array());

        return parent::getSituacaoFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
