<?php echo $this->headScript()->prependFile($this->basePath('js/funcionario/funcionario.js')); ?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Funcionários</h2>
        </div>
        <div class="col-md-6">
            <div class="pull-right"><a class="btn btn-default" style="margin-top: 22px;" href="/application/funcionario/adicionarFuncionario"><i class="fa fa-user-plus"></i> Adicionar</a></div>
        </div>
    </div>
    <!--<hr>-->
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" style="background: white">
                <thead>
                    <tr>
                        <th>Nome:</th>
                        <th>Cargo:</th>
                        <th>Ação:</th>
                    </tr>
                </thead>
                <tbody>        
                    <?php foreach ($this->funcionarios as $listFunc): ?>

                        <tr class="<?php echo $this->funcionarioHelper()->traduzStatusFuncionario($listFunc->getSituacaoFunc())['classeLinha']; ?>">
                            <td><?php echo strtoupper($listFunc->getNomeFunc()) ?></td>
                            <td><?php echo strtoupper($listFunc->getFuncaoFunc()) ?></td>
                            <td><a href="/application/funcionario/adicionar-funcionario/<?php echo $listFunc->getIdFunc()?>"><i class="fa fa-pencil-square-o fa-fw center-block"></i></a></td>
                        </tr>  
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

</div>




