<style>
    #boxLogin{
        width: 600px;
        height: 400px;

        border: 0px rgb(89,89,89) solid;

        -webkit-box-sizing: content-box;
        -moz-box-sizing: content-box;
        box-sizing: content-box;

        background: rgb(255,255,255);

        text-shadow: 0px 0px 0px rgb(89,89,89);

        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;

        -moz-box-shadow: inset -6px -2px 0px 0px rgb(128,128,128);
        -webkit-box-shadow: inset -6px -2px 0px 0px rgb(128,128,128);
        box-shadow: inset -6px -2px 0px 0px rgb(128,128,128);

        position:absolute;
        top:50%;
        left:50%;
        margin-top:-200px;
        margin-left:-300px;
    }
    .col-md-offset-3{
        margin-left: 28%;
    }
</style>
<div id="boxLogin">
    <div id="logo" style="height: 220px; text-align: center; margin-top: 5px">

        <img src="<?php echo $this->basePath('img/logoSisBaluBig.png') ?>" alt="..." class="img-rounded">
        <!--<h1>SisBalu</h1>-->
        <h3>Sejam bem-vindos!</h3>
        
    </div>
    <hr style="width: 100px; width: 570px;">
    <div id="formLogin" style="height: 300px; margin-top: -9px;">
        <?php $this->form->prepare(); ?>
        <?php echo $this->form()->openTag($this->form); ?>

        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <div class="form-group">
                    <div class="col-sm-7">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user"></i></span>
                            <?php echo $this->formInput($this->form->get('usuarioFunc')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <div class="form-group">
                    <div class="col-sm-7">  
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><i class="fa fa-key fa-flip-vertical"></i></span>
                            <?php echo $this->formInput($this->form->get('senhaFunc')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                    <?php echo $this->formButton()->openTag($form->get('submit')); ?>
                    <?php echo $form->get('submit')->getLabel().' <i class="fa fa-sign-in"></i>'; ?>
                    <?php echo $this->formButton()->closeTag(); ?>
            </div>
        </div>


        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

