<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('SIS-BALU'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/application.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-ui.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <style>
            body{
                background: gainsboro;
            }
            
            .iconMenu{
                position: relative;
                margin: -10px 30%;
            }
            .menuPrincipal, .menuPrincipal a{
                height: 60px;
            }
            .menuPrincipal p{
                font-size: small;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-default navbar-fixed-top">
                        <div class="container">
                            <div class="navbar-header pull-left">
                                <a class="navbar-brand" href="#">
                                    <img alt="Brand" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>
                                </a>
                            </div>
                            <ul class="nav navbar-nav">
                                <li id="inicio" class="menuPrincipal"><a href="<?php echo $this->basePath('application/index/index') ?>"><i class="fa fa-th-large fa-2x iconMenu"></i><p>INICIAL</p></a></li>
                                <li id=" vendedor" class="menuPrincipal"><a href="<?php echo $this->basePath('application/vendedor/index') ?>"><i class="fa fa-users fa-2x fa-fw iconMenu"></i><p>VENDEDOR</p></a></li>
                                <li id="estoque" class="menuPrincipal"><a href="<?php echo $this->basePath('application/estoque/index') ?>"><i class="fa fa-cubes fa-2x fa-fw iconMenu"></i><p>ESTOQUE</p></a></li> 
                                <li id="fornecedor" class="menuPrincipal"><a href="<?php echo $this->basePath('application/fornecedor/index') ?>"><i class="fa fa-truck fa-2x fa-fw iconMenu"></i><p>FORNECEDOR</p></a></li> 
                                <li id="funcionario" class="menuPrincipal"><a href="<?php echo $this->basePath('application/funcionario/index') ?>"><i class="fa fa-male fa-2x fa-fw iconMenu" ></i><p>FUNCIONÁRIO</p></a></li> 
                                <li id="relatorio" class="menuPrincipal"><a href="#"><i class="fa fa-book fa-2x fa-fw iconMenu"></i><p>RELATÓRIOS</p></a></li> 
                            </ul>
                            <div class="navbar-header pull-right">
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="height: 49px;">
                                        <span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li><a href="#">Perfil</a></li>
                                        <li><a href="/application/auth/logout">Logout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>

        </div> <!-- /container -->
        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
                <footer style="text-align: center">
                    <p>&copy; 2015 - <?php echo date('Y') ?> por PIM Tecnologia Todos os direitos reservados</p>
                </footer>
            </div>
        </nav>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
